# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d29bb2eeb2933e90c23fcb7a8cbedcfeed84ec37620ff47de61a37cee92a7c9e4e800ceb9d5ae7607f92c9467373ecf3417f508731a3c6e349cd602394a28304

test:
  secret_key_base: 8fae47beca5e65ff45f65ec94b833d60f62bd5bdbc79a5de7e87670a2b291309df16cdac57088d9d465677808e374cc7cad85d6ed03c34419e582bb5e2f691db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: eaccffd1c5d594d4bf8307cac62cddb0870cdfa795bf2257ca173bedabc389a399b066e3b48cc0544604a4a77da38b9af4b46448fdad2efac9b668a18ad47ddf#<%= ENV["SECRET_KEY_BASE"] %>

